version: '3.8'
services:
  ost-hp-admin:
    container_name: ost-hp-admin
    image: webdevops/php-nginx:8.3-alpine
    volumes:
      - ../:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../ost_hp/ost-hp/public/uploads:/app/public/uploads
    ports:
      - '8014:80'
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - TZ=Asia/Tokyo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - project-network

networks:
  project-network:
    driver: bridge
